=== VicdeJuan/SI/P3/data/history.dtd
<!ELEMENT catalog (pedido)*>
        <!ELEMENT pedido (movie)*>
        <!ELEMENT movie (id|quantity|date)*>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT quantity (#PCDATA)>
        <!ELEMENT date (#PCDATA)>

=== VicdeJuan/SI/P2/users/asdf@asdf/history.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE note SYSTEM "/data/history.dtd">
<catalog>
<pedido><movie><id>0</id><quantity>1</quantity><date>2014-10-31T11:38:14+01:00</date></movie><movie><id>1</id><quantity>2</quantity><date>2014-10-31T11:38:14+01:00</date></movie><movie><id>2</id><quantity>1</quantity><date>2014-10-31T11:38:14+01:00</date></movie></pedido><pedido><movie><id>4</id><quantity>1</quantity><date>2014-10-31T11:38:19+01:00</date></movie><movie><id>3</id><quantity>1</quantity><date>2014-10-31T11:38:19+01:00</date></movie></pedido><pedido><movie><id>1</id><quantity>3</quantity><date>2014-10-31T11:38:40+01:00</date></movie><movie><id>5</id><quantity>1</quantity><date>2014-10-31T11:38:40+01:00</date></movie><movie><id>6</id><quantity>1</quantity><date>2014-10-31T11:38:40+01:00</date></movie><movie><id>0</id><quantity>2</quantity><date>2014-10-31T11:38:40+01:00</date></movie><movie><id>9</id><quantity>2</quantity><date>2014-10-31T11:38:40+01:00</date></movie></pedido></catalog>
