=== VicdeJuan/SI/P1/data/catalog.dtd
<!DOCTYPE catalog[

<!ENTITY COMPANY "JD Power Tools, Inc.">

<!ELEMENT catalog (movies+)>
<!ELEMENT movie (img,score,genre+,title,description)>
<!ELEMENT img (#PCDATA)>
<!ELEMENT score (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT description (#PCDATA)>
]>

=== VicdeJuan/SI/P1/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style/moviecatalog.xsl"?>
<!DOCTYPE note SYSTEM "data/catalog.dtd">

<catalog>
	<movie>
		<img>img/movie.jpg</img>
		<score>5</score>
		<genre>Comedia</genre>
		<title> Titulo </title>
		<description> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates nisi iure maxime. Omnis voluptate amet, ullam, minus architecto vitae doloremque, sunt aperiam dolorum quod tempora eaque fugit dignissimos facere est.</description>
	</movie>

	<movie>
		<img>img/movie.jpg</img>
		<score>5</score>
		<genre>Comedia</genre>
		<title> Titulo </title>
		<description> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit quos ad laborum, facere quasi amet officiis dolores odit maxime, ipsam corporis magni asperiores fuga eum soluta labore. Eveniet, beatae, ipsa!</description>
	</movie>

	<movie>
		<img>img/movie.jpg</img>
		<score>5</score>
		<genre>Comedia</genre>
		<title> Titulo </title>
		<description> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem nisi est inventore, vitae nemo iste non quisquam aspernatur similique unde itaque repellendus corrupti blanditiis necessitatibus quod a beatae commodi ratione!</description>
	</movie>


	<movie>
		<img>img/movie.jpg</img>
		<score>5</score>
		<genre>Comedia</genre>
		<title> Titulo </title>
		<description> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum architecto inventore, eveniet aspernatur consequuntur vero dolor tempore vitae quibusdam repellendus, sit, velit optio quidem, praesentium hic facere nemo laudantium non.</description>
	</movie>

	<movie>
		<img>img/movie.jpg</img>
		<score>5</score>
		<genre>Comedia</genre>
		<title> Titulo </title>
		<description> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima, iusto culpa molestias necessitatibus quisquam explicabo fugiat cumque vitae. Velit molestias nesciunt, ullam obcaecati numquam doloribus tenetur illo dolorum natus facilis.</description>
	</movie>

	<movie>
		<img>img/movie.jpg</img>
		<score>5</score>
		<genre>Comedia</genre>
		<title> Titulo </title>
		<description> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam, necessitatibus reprehenderit. Magnam ratione facilis commodi sapiente consequuntur, saepe, dolorum, sed placeat dolore pariatur inventore laboriosam minus autem soluta sit architecto!</description>
	</movie>


	<movie>
		<img>img/movie.jpg</img>
		<score>5</score>
		<genre>Comedia</genre>
		<title> Titulo </title>
		<description> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos itaque, officia pariatur nulla repellendus aspernatur! Labore, ut temporibus animi omnis officiis non libero nostrum deleniti quisquam voluptatem rem ducimus commodi?</description>
	</movie>

	<movie>
		<img>img/movie.jpg</img>
		<score>5</score>
		<genre>Comedia</genre>
		<title> Titulo </title>
		<description> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus perspiciatis, tempore excepturi pariatur accusamus nobis eos iure sed ipsum necessitatibus consequuntur, numquam, assumenda. Odit ipsam quod molestiae nesciunt perspiciatis, placeat.</description>
	</movie>


	<movie>
		<img>img/movie.jpg</img>
		<score>5</score>
		<genre>Comedia</genre>
		<title> Titulo </title>
		<description> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo libero odio mollitia perspiciatis minima cum praesentium earum nisi, aliquid quos aperiam ullam labore doloremque, nemo optio consequatur temporibus, quibusdam, numquam.</description>
	</movie>

</catalog>
