=== VicdeJuan/SI/P2/data/catalog.dtd
<!ELEMENT catalog (movie)*>
        <!ELEMENT movie (id|image|score|genre|title|year|description|price)*>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT image (#PCDATA)>
        <!ELEMENT score (#PCDATA)>
        <!ELEMENT genre (#PCDATA)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT year (#PCDATA)>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT price (#PCDATA)>

=== VicdeJuan/SI/P2/data/movies.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style/moviecatalog.xsl"?>
<!DOCTYPE note SYSTEM "data/catalog.dtd">

<catalog>
	<movie>
		<id>0</id>
		<image>img/tt0133093.jpg</image>
		<score>8.7</score>
		<genre>Action</genre>
		<title>The Matrix</title>
		<year>1999</year>
		<description>A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.</description>
		<price>3</price>
	</movie>
	<movie>
		<id>1</id>
		<image>img/tt0111161.jpg</image>
		<score>9.3</score>
		<genre>Crime</genre>
		<title>The Shawshank Redemption</title>
		<year>1994</year>
		<description>Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.</description>
		<price>2</price>
	</movie>
	<movie>
		<id>2</id>
		<image>img/tt0068646.jpg</image>
		<score>9.2</score>
		<genre>Crime</genre>
		<title>The Godfather</title>
		<year>1972</year>
		<description>The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.</description>
		<price>8</price>
	</movie>
	<movie>
		<id>3</id>
		<image>img/tt0071562.jpg</image>
		<score>9.1</score>
		<genre>Crime</genre>
		<title>The Godfather: Part II</title>
		<year>1974</year>
		<description>The early life and career of Vito Corleone in 1920s New York is portrayed while his son, Michael, expands and tightens his grip on his crime syndicate stretching from Lake Tahoe, Nevada to pre-revolution 1958 Cuba.</description>
		<price>3</price>
	</movie>
	<movie>
		<id>4</id>
		<image>img/tt0468569.jpg</image>
		<score>9</score>
		<genre>Action</genre>
		<title>The Dark Knight</title>
		<year>2008</year>
		<description>When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, the caped crusader must come to terms with one of the greatest psychological tests of his ability to fight injustice.</description>
		<price>2</price>
	</movie>
	<movie>
		<id>5</id>
		<image>img/tt0110912.jpg</image>
		<score>9</score>
		<genre>Crime</genre>
		<title>Pulp Fiction</title>
		<year>1994</year>
		<description>The lives of two mob hit men, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.</description>
		<price>4</price>
	</movie>
	<movie>
		<id>6</id>
		<image>img/tt0060196.jpg</image>
		<score>9</score>
		<genre>Western</genre>
		<title>The Good, the Bad and the Ugly</title>
		<year>1966</year>
		<description>A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.</description>
		<price>2</price>
	</movie>
	<movie>
		<id>7</id>
		<image>img/tt0108052.jpg</image>
		<score>8.9</score>
		<genre>Biography</genre>
		<title>Schindler's List</title>
		<year>1993</year>
		<description>In Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.</description>
		<price>4</price>
	</movie>
	<movie>
		<id>8</id>
		<image>img/tt0050083.jpg</image>
		<score>8.9</score>
		<genre>Drama</genre>
		<title>12 Angry Men</title>
		<year>1957</year>
		<description>A dissenting juror in a murder trial slowly manages to convince the others that the case is not as obviously clear as it seemed in court.</description>
		<price>6</price>
	</movie>
	<movie>
		<id>9</id>
		<image>img/tt0167260.jpg</image>
		<score>8.9</score>
		<genre>Action</genre>
		<title>The Lord of the Rings: The Return of the King</title>
		<year>2003</year>
		<description>Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.</description>
		<price>1</price>
	</movie>
	<movie>
		<id>10</id>
		<image>img/tt0137523.jpg</image>
		<score>8.9</score>
		<genre>Drama</genre>
		<title>Fight Club</title>
		<year>1999</year>
		<description>An insomniac office worker looking for a way to change his life crosses paths with a devil-may-care soap maker and they form an underground fight club that evolves into something much, much more...</description>
		<price>8</price>
	</movie>
	<movie>
		<id>11</id>
		<image>img/tt0120737.jpg</image>
		<score>8.8</score>
		<genre>Action</genre>
		<title>The Lord of the Rings: The Fellowship of the Ring</title>
		<year>2001</year>
		<description>A meek hobbit of the Shire and eight companions set out on a journey to Mount Doom to destroy the One Ring and the dark lord Sauron.</description>
		<price>2</price>
	</movie>
	<movie>
		<id>12</id>
		<image>img/tt0080684.jpg</image>
		<score>8.8</score>
		<genre>Action</genre>
		<title>Star Wars: Episode V - The Empire Strikes Back</title>
		<year>1980</year>
		<description>After the rebels have been brutally overpowered by the Empire on their newly established base, Luke Skywalker takes advanced Jedi training with Master Yoda, while his friends are pursued by Darth Vader as part of his plan to capture Luke.</description>
		<price>4</price>
	</movie>
	<movie>
		<id>13</id>
		<image>img/tt1375666.jpg</image>
		<score>8.8</score>
		<genre>Action</genre>
		<title>Inception</title>
		<year>2010</year>
		<description>A thief who steals corporate secrets through use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.</description>
		<price>2</price>
	</movie>
	<movie>
		<id>14</id>
		<image>img/tt0109830.jpg</image>
		<score>8.8</score>
		<genre>Drama</genre>
		<title>Forrest Gump</title>
		<year>1994</year>
		<description>Forrest Gump, while not intelligent, has accidentally been present at many historic moments, but his true love, Jenny Curran, eludes him.</description>
		<price>8</price>
	</movie>
	<movie>
		<id>15</id>
		<image>img/tt0073486.jpg</image>
		<score>8.8</score>
		<genre>Drama</genre>
		<title>One Flew Over the Cuckoo's Nest</title>
		<year>1975</year>
		<description>Upon admittance to a mental institution, a brash rebel rallies the patients to take on the oppressive head nurse.</description>
		<price>8</price>
	</movie>
	<movie>
		<id>16</id>
		<image>img/tt0167261.jpg</image>
		<score>8.8</score>
		<genre>Action</genre>
		<title>The Lord of the Rings: The Two Towers</title>
		<year>2002</year>
		<description>While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.</description>
		<price>1</price>
	</movie>
	<movie>
		<id>17</id>
		<image>img/tt0099685.jpg</image>
		<score>8.7</score>
		<genre>Biography</genre>
		<title>Goodfellas</title>
		<year>1990</year>
		<description>Henry Hill and his friends work their way up through the mob hierarchy.</description>
		<price>7</price>
	</movie>
	<movie>
		<id>18</id>
		<image>img/tt0133093.jpg</image>
		<score>8.7</score>
		<genre>Action</genre>
		<title>The Matrix</title>
		<year>1999</year>
		<description>A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.</description>
		<price>5</price>
	</movie>
	<movie>
		<id>19</id>
		<image>img/tt0076759.jpg</image>
		<score>8.7</score>
		<genre>Action</genre>
		<title>Star Wars</title>
		<year>1977</year>
		<description>Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a wookiee and two droids to save the universe from the Empire's world-destroying battle-station, while also attempting to rescue Princess Leia from the evil Darth Vader.</description>
		<price>1</price>
	</movie>
	<movie>
		<id>20</id>
		<image>img/tt0047478.jpg</image>
		<score>8.7</score>
		<genre>Drama</genre>
		<title>Seven Samurai</title>
		<year>1954</year>
		<description>A poor village under attack by bandits recruits seven unemployed samurai to help them defend themselves.</description>
		<price>1</price>
	</movie>
	<movie>
		<id>21</id>
		<image>img/tt0317248.jpg</image>
		<score>8.7</score>
		<genre>Crime</genre>
		<title>City of God</title>
		<year>2002</year>
		<description>Two boys growing up in a violent neighborhood of Rio de Janeiro take different paths: one becomes a photographer, the other a drug dealer.</description>
		<price>5</price>
	</movie>
	<movie>
		<id>22</id>
		<image>img/tt0114369.jpg</image>
		<score>8.7</score>
		<genre>Drama</genre>
		<title>Se7en</title>
		<year>1995</year>
		<description>Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his modus operandi.</description>
		<price>8</price>
	</movie>
	<movie>
		<id>23</id>
		<image>img/tt0114814.jpg</image>
		<score>8.7</score>
		<genre>Crime</genre>
		<title>The Usual Suspects</title>
		<year>1995</year>
		<description>A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which begin when five criminals meet at a seemingly random police lineup.</description>
		<price>2</price>
	</movie>
	<movie>
		<id>24</id>
		<image>img/tt0102926.jpg</image>
		<score>8.6</score>
		<genre>Crime</genre>
		<title>The Silence of the Lambs</title>
		<year>1991</year>
		<description>A young F.B.I. cadet must confide in an incarcerated and manipulative killer to receive his help on catching another serial killer who skins his victims.</description>
		<price>5</price>
	</movie>
	<movie>
		<id>25</id>
		<image>img/tt0038650.jpg</image>
		<score>8.7</score>
		<genre>Drama</genre>
		<title>It's a Wonderful Life</title>
		<year>1946</year>
		<description>An angel helps a compassionate but despairingly frustrated businessman by showing what life would have been like if he never existed.</description>
		<price>2</price>
	</movie>
	<movie>
		<id>26</id>
		<image>img/tt0064116.jpg</image>
		<score>8.7</score>
		<genre>Western</genre>
		<title>Once Upon a Time in the West</title>
		<year>1968</year>
